In [105]:
import pandas as pd

In [106]:
import numpy as np

In [107]:
conj_input = pd.read_csv(r"C:\Users\ManasiAdmin\Desktop\DELL HACK\Traditional-Conjoint-Analysis-with-Python-master\ConJointInput.csv",sep = ";")

In [108]:
conj_input

   Stimulus  Rank
0    A1B1C1     2
1    A1B1C2     3
2    A1B1C3     1
3    A1B2C1     5
4    A1B2C2     6
5    A1B2C3     4
6    A2B1C1     8
7    A2B1C2     9
8    A2B1C3     7
9    A2B2C1    11
10   A2B2C2    12
11   A2B2C3    10
12   A3B1C1    14
13   A3B1C2    15
14   A3B1C3    13
15   A3B2C1    17
16   A3B2C2    18
17   A3B2C3    16

In [109]:
ConjointDummyDF = pd.DataFrame(np.zeros((18,9)), columns=["Rank","A1", "A2", "A3",
                                                    "B1","B2", 
                                                    "C1", "C2",
                                                    "C3"])
ConjointDummyDF

    Rank   A1   A2   A3   B1   B2   C1   C2   C3
0    0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
1    0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
2    0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
3    0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
4    0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
5    0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
6    0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
7    0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
8    0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
9    0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
10   0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
11   0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
12   0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
13   0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
14   0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
15   0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
16   0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
17   0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0

In [110]:
ConjointDummyDF.Rank = conj_input.Rank

for index, row in conj_input.iterrows(): 
    stimuli1, stimuli2, stimuli3 = conj_input["Stimulus"].ix[index][:2], \
    conj_input["Stimulus"].ix[index][2:4], conj_input["Stimulus"].ix[index][4:6]
    
    
    ConjointDummyDF.ix[index, [stimuli1,stimuli2,stimuli3]] = 1

C:\Users\ManasiAdmin\Anaconda3\lib\site-packages\ipykernel_launcher.py:4: DeprecationWarning:
.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/indexing.html#ix-indexer-is-deprecated
  after removing the cwd from sys.path.
C:\Users\ManasiAdmin\Anaconda3\lib\site-packages\ipykernel_launcher.py:7: DeprecationWarning:
.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/indexing.html#ix-indexer-is-deprecated
  import sys

In [111]:
ConjointDummyDF.head()

   Rank   A1   A2   A3   B1   B2   C1   C2   C3
0     2  1.0  0.0  0.0  1.0  0.0  1.0  0.0  0.0
1     3  1.0  0.0  0.0  1.0  0.0  0.0  1.0  0.0
2     1  1.0  0.0  0.0  1.0  0.0  0.0  0.0  1.0
3     5  1.0  0.0  0.0  0.0  1.0  1.0  0.0  0.0
4     6  1.0  0.0  0.0  0.0  1.0  0.0  1.0  0.0

In [112]:
fullNames = {"Rank":"Rank", \
           "A1": "i3 (processor)","A2": "i5 (processor)","A3": "i7 (processor)", \
          "B1": "4GB", "B2":"8GB", \
           "C1":"1", "C2":"2", "C3": "3",\
          }

ConjointDummyDF.rename(columns=fullNames, inplace=True)

In [113]:
df = pd.read_csv(r"C:\Users\ManasiAdmin\Desktop\DELL HACK\Online_Retail_final_final.csv")

In [114]:
ConjointDummyDF.head()

,Rank,i3 (processor),i5 (processor),i7 (processor),4GB,8GB,1,2,3
0,2,1.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0
1,3,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0
2,1,1.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0
3,5,1.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0
4,6,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0

In [115]:
import statsmodels.api as sm

In [116]:
ConjointDummyDF.columns

Index(['Rank', 'i3 (processor)', 'i5 (processor)', 'i7 (processor)', '4GB',
       '8GB', '1', '2', '3'],
      dtype='object')

In [118]:
X = ConjointDummyDF[[u'i3 (processor)', u'i5 (processor)', u'i7 (processor)', u'4GB',\
       u'8GB', u'1', u'2', u'3']]
X = sm.add_constant(X)
Y = ConjointDummyDF.Rank
linearRegression = sm.OLS(Y, X). fit()
linearRegression.summary()

C:\Users\ManasiAdmin\Anaconda3\lib\site-packages\scipy\stats\stats.py:1394: UserWarning: kurtosistest only valid for n>=20 ... continuing anyway, n=18
  "anyway, n=%i" % int(n))

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:                   Rank   R-squared:                       1.000
Model:                            OLS   Adj. R-squared:                  1.000
Method:                 Least Squares   F-statistic:                 3.410e+30
Date:                Mon, 19 Nov 2018   Prob (F-statistic):          1.78e-180
Time:                        17:03:46   Log-Likelihood:                 569.68
No. Observations:                  18   AIC:                            -1127.
Df Residuals:                      12   BIC:                            -1122.
Df Model:                           5
Covariance Type:            nonrobust
==================================================================================
                     coef    std err          t      P>|t|      [0.025      0.975]
----------------------------------------------------------------------------------
const              4.3846    5.8e-16   7.56e+15      0.000       4.385       4.385
i3 (processor)    -4.5385   1.79e-15  -2.54e+15      0.000      -4.538      -4.538
i5 (processor)     1.4615   1.79e-15   8.18e+14      0.000       1.462       1.462
i7 (processor)     7.4615   1.79e-15   4.17e+15      0.000       7.462       7.462
4GB                0.6923   1.29e-15   5.37e+14      0.000       0.692       0.692
8GB                3.6923   1.29e-15   2.86e+15      0.000       3.692       3.692
1                  1.4615   1.79e-15   8.18e+14      0.000       1.462       1.462
2                  2.4615   1.79e-15   1.38e+15      0.000       2.462       2.462
3                  0.4615   1.79e-15   2.58e+14      0.000       0.462       0.462
==============================================================================
Omnibus:                        1.433   Durbin-Watson:                   0.743
Prob(Omnibus):                  0.488   Jarque-Bera (JB):                0.868
Skew:                           0.062   Prob(JB):                        0.648
Kurtosis:                       1.931   Cond. No.                     9.92e+16
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The smallest eigenvalue is 3.96e-33. This might indicate that there are
strong multicollinearity problems or that the design matrix is singular.
"""

In [120]:
importance = []
relative_importance = []

rangePerFeature = []

begin = "A"
tempRange = []
for stimuli in fullNames.keys():
    if stimuli[0] == begin:
        tempRange.append(linearRegression.params[fullNames[stimuli]])
    elif stimuli == "Rank":
        rangePerFeature.append(tempRange)
    else:
        rangePerFeature.append(tempRange)
        begin = stimuli[0]
        tempRange = [linearRegression.params[fullNames[stimuli]]]

In [122]:
for item in rangePerFeature:
    importance.append( max(item) - min(item))

for item in importance:
    relative_importance.append(100* round(item/sum(importance),3))

In [124]:
partworths = []

item_levels = [1,3,5,8]

for i in range(1,4):
    part_worth_range = linearRegression.params[item_levels[i-1]:item_levels[i]]
    print(part_worth_range)

i3 (processor)   -4.538462
i5 (processor)    1.461538
dtype: float64
i7 (processor)    7.461538
4GB               0.692308
dtype: float64
8GB    3.692308
1      1.461538
2      2.461538
dtype: float64

In [126]:
meanRank = []
for i in ConjointDummyDF.columns[1:]:
    newmeanRank = ConjointDummyDF["Rank"].loc[ConjointDummyDF[i] == 1].mean()
    meanRank.append(newmeanRank)

    
#total Mean or, "basic utility" is used as the "zero alternative"
totalMeanRank = sum(meanRank) / len(meanRank)



partWorths = {}
for i in range(len(meanRank)):
    name = fullNames[sorted(fullNames.keys())[i]]
    partWorths[name] = meanRank[i] - totalMeanRank

In [128]:
partWorths

{'i3 (processor)': -6.0,
 'i5 (processor)': 0.0,
 'i7 (processor)': 6.0,
 '4GB': -1.5,
 '8GB': 1.5,
 '1': 0.0,
 '2': 1.0,
 '3': -1.0}

In [130]:
print("Relative Importance of Feature:\n\nProcessor:",relative_importance[0], "%",\
"\nRAM:", relative_importance[1], "%", "\nWarranty:", relative_importance[2], "%\n\n")

print ("--"*30)

print ("Importance of Feature:\n\nProcessor:",importance[0],\
"\nRAM:", importance[1],  "\nWarranty:", importance[2])

Relative Importance of Feature:

Processor: 44.4 %
RAM: 44.4 %
Warranty: 11.1 %


------------------------------------------------------------
Importance of Feature:

Processor: 11.999999999999993
RAM: 11.999999999999993
Warranty: 3.0000000000000013